services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my_express_app_dev_server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/TodoDb
    env_file:
      - ./server/.env
    command: npm run dev
    working_dir: /app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: my_express_app_dev_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    working_dir: /app
